version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python-pip
      - pip install --upgrade python
      - pip install --upgrade awscli
  pre_build:
    commands:
      - IMAGE_NAME="${REPOSITORY_URI}:$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)"
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - echo Build started on $(date)
      - docker build --tag ${IMAGE_NAME} .
      - docker push ${IMAGE_NAME}
  post_build:
    commands:
      - echo Build completed on $(date)
      - printf '{"Parameters":{"Subnet":"%s", "SecurityGroup":"%s", "DockerImage":"%s"}}' ${Subnet} ${SecurityGroup} ${IMAGE_NAME} > config.json

artifacts:
  files: config.json
